# Generated by Django 5.0 on 2023-12-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='published_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='content',
            new_name='description',
        ),
    ]
