# Generated by Django 5.0 on 2023-12-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0003_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
