# Generated by Django 5.0 on 2023-12-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0005_alter_comments_options_alter_comments_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=400, verbose_name=''),
        ),
    ]
