# Generated by Django 5.0 on 2023-12-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0010_blogposter_alter_post_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='image',
        ),
    ]
