# Generated by Django 5.0 on 2023-12-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0012_blogposter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to='project/media/itempics', verbose_name='Постер'),
        ),
    ]
