# Generated by Django 5.0 on 2023-12-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0013_alter_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blogpics', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='Blogposter',
        ),
    ]
