# Generated by Django 5.0 on 2024-01-08 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0016_remove_order_items_remove_order_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
