# Generated by Django 5.0 on 2024-01-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0022_remove_order_delivery_time_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
    ]
