# Generated by Django 5.0 on 2024-01-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop', '0023_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
